# This file contains values from Cookiecutter

default_context:
  project_name: "datafirst-tools"
  project_description: "Tools to handle the DataFirst program"
  organization: "ckids-datafirst"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "ckids_datafirst"
  email: "maxiosorio@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
